spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: localhost
    port: 6379

jwt:
  issuer: test
  secret-key: twk4jbz8a6smC4u0Xv6KvQUImMfVZ16/SCR0uKJIv3g=
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 3600000

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    s3:
      bucket: test
    region:
      static: ap-northeast-2
    stack:
      auto: false
