spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs/json
