server:
  port: 8082
  forward-headers-strategy: framework

spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs/json
